### ISSUE TITLE
Add TradingMode data to aegis, configure grafana dashboard and alerts

### ISSUE THREAD

**Issue by ninocomputer** [mento-protocol/aegis#2]
**Description**

We want to alert based on changes in trading mode for a rate feed.
In order to do this we can just configure metrics based on the `getRateFeedTradingMode` function in the `BreakerBox`, for all the rate feeds.

Then we can create a dashboard and severe alerts if the circuit breaker breaks and the trading mode is changed.

**Acceptance Criteria:**

- [x] On-chain data is created in Aegis
- [x] Dashboard is created 
- [x] Alert is created that pages on-call

**Comment by baroooo** [comment]
https://clabsmento.grafana.net/goto/RRJ2TgkIR?orgId=1
https://clabsmento.grafana.net/goto/-SxoTRzSR?orgId=1
https://clabsmento.grafana.net/goto/4HZ0oRkIR?orgId=1
