### ISSUE TITLE
Add last updated timestamp to aegis and use it in alerts

### ISSUE THREAD

**Issue by bowd** [mento-protocol/aegis#3]
**Description**

In order to check that aegis is running correctly and the data is up to date, its useful to export a timestamp for last updated at, which we can use to alert if it gets stale.

**Acceptance criteria**

- [x] Add a system metric to aegis for last updated at.
- [x] Create an alert

**Comment by baroooo** [comment]
Does the timestamp mentioned here come from contract or it is just the timestamp of the aegis fetching the data? If it is the second, I assume prometheus would keep a timestamp for each update, can't we just use that ?

**Comment by baroooo** [comment]
I was expecting it to be a sawtooth but it is not. it is constant at 26s :/
<img width="1461" alt="image" src="https://github.com/mento-protocol/aegis/assets/17413894/121b8eae-d3cf-48d2-9948-bc86feafe125">

**Comment by baroooo** [comment]
https://clabsmento.grafana.net/goto/HWwfl8RIR?orgId=1
